import { type Metadata } from "next"
import Link from "next/link"
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className='flex justify-between items-center p-4 gap-4 h-16'>
            <Link href='http://localhost:3000/'>
              <div>LOGO</div>
            </Link>
            <nav>
              <ul className='flex gap-4'>
                <Link
                  href='http://localhost:3000/issues'
                  className='hover:underline'
                >
                  <li>Application</li>
                </Link>
                <Link href='http://localhost:3000/leaderboards'>
                  <li className='hover:underline'>Leaderboard</li>
                </Link>
              </ul>
            </nav>
            <div className='flex gap-4'>
              <SignedOut>
                <SignInButton mode='modal' />
                <SignUpButton mode='modal' />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {modal}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
